#ifndef _DEFINITIONS_H_
#define _DEFINITIONS_H_

#define MAIN_MENU_INDEX 0
#define MATCH_MENU_INDEX 1

#define MATCH_MAIN_OPTION_INDEX 0
#define MATCH_MAIN_OPTION_X 72
#define MATCH_MAIN_OPTION_Y 64
#define MATCH_MAIN_OPTION_H 6

#define CHAR_1_OPTION_INDEX 0
#define CHAR_1_OPTION_X 32
#define CHAR_1_OPTION_Y 72
#define CHAR_1_OPTION_H 4

#define MATCH_MODE_OPTION_INDEX 1
#define MATCH_MODE_OPTION_X 72
#define MATCH_MODE_OPTION_Y 64
#define MATCH_MODE_OPTION_H 3

#define PLAY_OPTION_INDEX 2
#define PLAY_OPTION_X 72
#define PLAY_OPTION_Y 96
#define PLAY_OPTION_H 2

#define CHAR_2_OPTION_INDEX 3
#define CHAR_2_OPTION_X 112
#define CHAR_2_OPTION_Y 72
#define CHAR_2_OPTION_H 4

#define CHAR_1_SPRITE_X 50
#define CHAR_1_SPRITE_Y 87
#define CHAR_2_SPRITE_X 118
#define CHAR_2_SPRITE_Y 87

#define MATCH_MODE_NUMBER_SPRITE_X 75
#define MATCH_MODE_DESCRIPTION_SPRITE_1_X 83
#define MATCH_MODE_DESCRIPTION_SPRITE_2_X 91
#define MATCH_MODE_DESCRIPTION_SPRITE_Y 80

#define MATCH_MODE_3_MIN 0
#define MATCH_MODE_5_MIN 1
#define MATCH_MODE_3_GOALS 2
#define MATCH_MODE_7_GOALS 3

#define CHAR_SPRITE_TILESET_START 20
#define CHAR_SPRITE_TILES_START_INDEX 20

#define NUMBER_SPRITE_TILES_START_INDEX 24

#define MATCH_MODE_DESCRIPTION_MIN_TILESET_START 12
#define MATCH_MODE_DESCRIPTION_GOALS_TILESET_START 14

// Match score
#define SCORE_GOAL_H_1_SPRITE_INDEX 0
#define SCORE_GOAL_H_2_SPRITE_INDEX 1
#define SCORE_GOAL_V_1_SPRITE_INDEX 2
#define SCORE_GOAL_V_2_SPRITE_INDEX 3

#define SCORE_GOAL_H_1_SPRITE_X 30
#define SCORE_GOAL_H_2_SPRITE_X 24
#define SCORE_GOAL_V_1_SPRITE_X 42
#define SCORE_GOAL_V_2_SPRITE_X 48
#define SCORE_GOAL_SPRITE_Y 24

// Match Time
#define TIME_DIVIDER_SPRITE_TILESET_INDEX 36

#define TIME_MIN_SPRITE_INDEX 4
#define TIME_DIVIDER_SPRITE_INDEX 5
#define TIME_SEC_1_SPRITE_INDEX 6
#define TIME_SEC_2_SPRITE_INDEX 7

#define TIME_MIN_SPRITE_X 137
#define TIME_DIVIDER_SPRITE_X 142
#define TIME_SEC_1_SPRITE_X 146
#define TIME_SEC_2_SPRITE_X 152
#define TIME_SPRITE_Y 24

// Goalposts
#define GOALPOST_SPRITE_TITESET_START_INDEX 37

#define GOALPOST_1_SPRITE_START_INDEX 8
#define GOALPOST_2_SPRITE_START_INDEX 16

#define GOALPOST_1_SPRITE_X 13
#define GOALPOST_2_SPRITE_X 155
#define GOALPOST_SPRITE_Y 94

// Ball
#define BALL_SPRITE_TITESET_START_INDEX 16
#define BALL_SPRITE_INDEX 24

#define BALL_SPRITE_MAX_X 160
#define BALL_SPRITE_MIN_Y 116

// Player
#define PLAYER_SPRITE_TITESET_START_INDEX 20
#define PLAYER_SPRITE_INDEX 25

#define PLAYER_SPRITE_MAX_X 160
#define PLAYER_SPRITE_MIN_Y 116

#define PLAYER_KICK_FORCE_X 200
#define PLAYER_KICK_FORCE_Y 700

// Labels
#define GOAL_LABEL_SPRITE_TITESET_START_INDEX 43
#define LABEL_SPRITE_START_INDEX 29

#endif