#ifndef _DEFINITIONS_H_
#define _DEFINITIONS_H_

#define MAIN_MENU_INDEX 0
#define MATCH_MENU_INDEX 1

#define MATCH_MAIN_OPTION_INDEX 0
#define MATCH_MAIN_OPTION_X 72
#define MATCH_MAIN_OPTION_Y 64
#define MATCH_MAIN_OPTION_H 6

#define CHAR_1_OPTION_INDEX 0
#define CHAR_1_OPTION_X 32
#define CHAR_1_OPTION_Y 72
#define CHAR_1_OPTION_H 4

#define MATCH_MODE_OPTION_INDEX 1
#define MATCH_MODE_OPTION_X 72
#define MATCH_MODE_OPTION_Y 64
#define MATCH_MODE_OPTION_H 3

#define PLAY_OPTION_INDEX 2
#define PLAY_OPTION_X 72
#define PLAY_OPTION_Y 96
#define PLAY_OPTION_H 2

#define CHAR_2_OPTION_INDEX 3
#define CHAR_2_OPTION_X 112
#define CHAR_2_OPTION_Y 72
#define CHAR_2_OPTION_H 4

#define CHAR_1_SPRITE_X 50
#define CHAR_1_SPRITE_Y 87
#define CHAR_2_SPRITE_X 118
#define CHAR_2_SPRITE_Y 87

#define MATCH_MODE_NUMBER_SPRITE_X 75
#define MATCH_MODE_DESCRIPTION_SPRITE_1_X 83
#define MATCH_MODE_DESCRIPTION_SPRITE_2_X 91
#define MATCH_MODE_DESCRIPTION_SPRITE_Y 80

#define MATCH_MODE_3_MIN 0
#define MATCH_MODE_5_MIN 1
#define MATCH_MODE_3_GOALS 2
#define MATCH_MODE_7_GOALS 3

#define CHAR_SPRITE_TILESET_START 20
#define CHAR_SPRITE_TILES_START_INDEX 20

#define NUMBER_SPRITE_TILES_START_INDEX 24

#define MATCH_MODE_DESCRIPTION_MIN_TILESET_START 12
#define MATCH_MODE_DESCRIPTION_GOALS_TILESET_START 14

#endif