/*

 GAME_MATCH_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\pontotel\personal\gbtd22\tiles\head_hit_menu.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GameMatchTilemapWidth 20
#define GameMatchTilemapHeight 18
#define GameMatchTilemapBank 0

extern unsigned char GameMatchTilemap[];

/* End of GAME_MATCH_TILEMAP.H */
