/*

 MAIN_MENU_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\pontotel\personal\gbtd22\tiles\head_hit_menu.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MainMenuTilemapWidth 20
#define MainMenuTilemapHeight 18
#define MainMenuTilemapBank 0

extern unsigned char MainMenuTilemap[];

/* End of MAIN_MENU_TILEMAP.H */
